version: '3'

volumes:
  mysql-db:

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=db-nest-blog
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3308
    command: npm run start:dev
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db-nest-blog
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - 3308:3306
